### ISSUE TITLE
Disable log4cpp support so we can compile on OpenWRT

### ISSUE THREAD

**Issue by hongkongkiwi** [uditha-atukorala/bitz-server#6]
Hi,

I'm working on a Makefile for OpenWRT as I would like to use bitz-server on some embedded hardware. Unfortunately OpenWRT disables log4cpp.

Is it possible to add a flag to disable log4cpp and just log to syslog or an external file?

By the way, I've already got the other dependencies compiling file ;)

**Comment by uatuko** [comment]
Hi, 

Sorry for not responding any sooner. I'm not actually happy with log4cpp and have thought of replacing it for sometime. 

I'll look into creating an internal logger so it can log either to files or use syslog but feel free to send a pull request if you have any ideas :).

**Comment by uatuko** [comment]
[spdlog](https://github.com/gabime/spdlog) seems interesting...
